# Hexo Configuration

# Site
title: to the core
subtitle: ricette per una vita più semplice
description: Come si fa il sapone? Come si fa il pane? Come fare una bevanda alcolica? Quali sono le ricette più essenziali?
author: Piero Ciarfaglia
language: it

# URL
url: https://tothecore.info
root: /
permalink: :title.html

# Directory
source_dir: source
public_dir: public_html

# Writing
new_post_name: :title.md
default_layout: recipe
titlecase: false
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 100
  order_by: date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
use_date_for_updated: false

# Pagination
per_page: 100
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Theme
theme: tothecore

# SASS
node_sass:
  debug: false
  outputStyle: compressed
  precision: 2
  sourceComments: false
  sourceMap: false

# Deployment
deploy:
  type: ''
